In [107]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Aim is to predict the marks of students of the test data

In [108]:
# Use the file namd 'training data' to train the model

data = pd.read_excel('Training data.xlsx')
x_train = np.array(data.iloc[:,0:8])
y_train = np.array(data.iloc[:,8]).reshape(-1,1)

# Try plotting y_train with different features
# To get an idea whether to add some features or not
# Add some features if required in x_train

# Also do label encoding for features not represented in numbers
# refer the link if not know : https://youtu.be/589nCGeWG1w?si=t2Wa7LgbUOO4RooM

def feature_changing(x_train):
  # ---------
    # Your code here
    def label_encode_column(column):
        _ , encoded = np.unique(column, return_inverse=True)
        return encoded

    col1_index = 0
    col2_index = 1

    x_train[:, col1_index] = label_encode_column(x_train[:, col1_index])
    x_train[:, col2_index] = label_encode_column(x_train[:, col2_index])
  # ---------
    return x_train

x_train = feature_changing(x_train)
print(x_train)

[[0 1 2 ... 6 18 118]
 [1 1 2 ... 7 19 107]
 [1 1 3 ... 5 18 108]
 ...
 [1 1 2 ... 5 17 123]
 [1 0 1 ... 8 17 104]
 [1 1 1 ... 6 18 128]]


In [109]:
def z_score(x_train):


  x_train= x_train.astype(np.float64)
  x_means = np.mean(x_train, axis=0)
  x_stds = np.std(x_train, axis=0)

  x_train = (x_train - x_means) / x_stds


  return x_train, x_means, x_stds



In [110]:
z_score(x_train)

(array([[-1.46446375e+00,  8.56213906e-01,  2.86766521e-01, ...,
          3.75906959e-01,  3.31807385e-02,  7.71401505e-01],
        [ 6.82843803e-01,  8.56213906e-01,  2.86766521e-01, ...,
          7.51438386e-01,  1.61321590e+00, -1.74154162e-01],
        [ 6.82843803e-01,  8.56213906e-01,  1.39826467e+00, ...,
          3.75531427e-04,  3.31807385e-02, -8.81945558e-02],
        ...,
        [ 6.82843803e-01,  8.56213906e-01,  2.86766521e-01, ...,
          3.75531427e-04, -1.54685443e+00,  1.20119954e+00],
        [ 6.82843803e-01, -1.16793244e+00, -8.24731623e-01, ...,
          1.12696981e+00, -1.54685443e+00, -4.32032980e-01],
        [ 6.82843803e-01,  8.56213906e-01, -8.24731623e-01, ...,
          3.75906959e-01,  3.31807385e-02,  1.63099757e+00]]),
 array([  0.682,   0.577,   1.742,   2.102,   3.191,   4.999,  17.979,
        109.026]),
 array([ 0.46569947,  0.49403542,  0.89968661,  0.92281959,  1.26827402,
         2.66289298,  0.63289731, 11.63337114]))

In [111]:

def cost(x_train,y_train,w,b):

  # ---------
    # Your code here
    y_hat= np.dot(x_train, w) + b
    m= y_train.shape[0]
    loss= np.mean((y_train- y_hat)**2)


    return loss

In [112]:
def gradient_descent(x_train,y_train,w,b):
  lr= 0.01
  #epochs= 1000
  m= y_train.shape[0]
  #for i in range(epochs):

  y_hat = np.dot(x_train, w) + b

  error = y_hat - y_train


  dj_dw = (1/m) * np.dot(x_train.T, error)
  dj_db = (1/m) * np.sum(error)


  w = w - lr * dj_dw
  b = b - lr * dj_db

  return w, b

In [113]:

x_train = x_train.astype(np.float64)
x_train,x_mean, x_std = z_score(x_train)

np.random.seed(2147483647)
w = np.random.randn(x_train.shape[1],1)
b = np.random.randn(1)

old_cost = 0

while abs(old_cost - cost(x_train,y_train,w,b))>0.00001:
  old_cost = cost(x_train,y_train,w,b)
  w,b = gradient_descent(x_train,y_train,w,b)

x_predict = pd.read_excel('Test data.xlsx').iloc[:,:8].to_numpy()
x_predict = feature_changing(x_predict)
x_predict = (x_predict - x_mean)/x_std
ans = pd.read_excel('Test data.xlsx').iloc[:,8].to_numpy()

y_predict = np.dot(x_predict,w) + b

accuracy = 0
for dim in range(len(ans)):
  if abs(y_predict[dim]-ans[dim])<0.5: # do not change the tolerance as you'll be checked on +- 0.5 error only
    accuracy += 1
accuracy = round(accuracy*100/200.0,2)
ok = 'Congratulations' if accuracy>95 else 'Optimization required'
print(f"{ok}, your accuracy is {accuracy}%")

Congratulations, your accuracy is 100.0%
